CREATE DATABASE IF NOT EXISTS task_manager;

CREATE USER IF NOT EXISTS 'task_user'@'192.168.57.11' IDENTIFIED BY 'task_password';
GRANT SELECT, INSERT, UPDATE, DELETE ON task_manager.* TO 'task_user'@'192.168.57.11';
FLUSH PRIVILEGES;

USE task_manager;

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

